### ISSUE TITLE
Data class delivered from QOBject?

### ISSUE THREAD

**Issue by HamedMasafi** [soroush/Qtz#3]
Why data class delivered from QObject? That must be converted to normal class (without QObject)

https://github.com/soroush/Qtz/blob/94ac5ed435cbaeff90c359fabc9c65c62c6716f2/qtz/core/qtz-single-core-application_p.hpp#L46

**Comment by soroush** [comment]
You mean "derived" right?
`Q_D`-family of macros require that.

**Comment by HamedMasafi** [comment]
No, it doesn't require. Check Qt itself source code!
